# Generated by Django 5.0.6 on 2024-07-15 08:24

import my_api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('discount', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arhive', models.BooleanField(default=False)),
                ('preview', models.ImageField(blank=True, null=True, upload_to=my_api_app.models.prod_prew_dir_path)),
            ],
            options={
                'verbose_name_plural': 'Продукты ',
                'ordering': ['name'],
            },
        ),
    ]
