# Generated by Django 5.0.6 on 2024-06-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_product_created_at_product_discount_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arhive',
            field=models.BooleanField(default=False),
        ),
    ]
