# Generated by Django 5.0.6 on 2024-07-09 11:54

import shop_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_alter_product_options_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=shop_app.models.prod_prew_dir_path),
        ),
    ]
